# Generated by Django 4.2.11 on 2026-03-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_groups_alter_user_is_active'),
        ('accounts', '0003_user_position_fk'),
    ]

    operations = [
    ]
