# Generated by Django 4.2.11 on 2026-03-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativecase',
            name='case_number',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Номер дела'),
        ),
        migrations.AlterField(
            model_name='casebasis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='seq_year',
            field=models.IntegerField(default=0, verbose_name='Год счётчика документов'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
