# Generated by Django 4.2.11 on 2026-03-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_administrativecase_case_number_and_more'),
        ('cases', '0010_taxauthoritydetails'),
    ]

    operations = [
    ]
