# Generated by Django 4.2.11 on 2026-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_merge_20260318_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxauthoritydetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
