# Generated by Django 4.2.11 on 2026-03-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_taxauthoritydetails_deputy_position'),
        ('cases', '0012_alter_taxauthoritydetails_id'),
    ]

    operations = [
    ]
