# Generated by Django 4.2.11 on 2026-03-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_taxauthoritydetails_refactor'),
        ('cases', '0013_merge_20260322_2320'),
    ]

    operations = [
    ]
