# Generated by Django 4.2.11 on 2026-03-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_cases_basis_category_m2m'),
        ('cases', '0014_merge_20260323_0459'),
    ]

    operations = [
    ]
