# Generated by Django 4.2.11 on 2026-03-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_cases_add_case_observers'),
        ('cases', '0015_merge_20260326_1838'),
    ]

    operations = [
    ]
