# Generated by Django 4.2.11 on 2026-03-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalflow',
            new_name='approvals_a_entity__6f174c_idx',
            old_name='approvals_entity_idx',
        ),
    ]
