# Generated by Django 4.2.11 on 2026-04-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('resolved', 'Исправлено'), ('rejected', 'Отклонено')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
