# Generated by Django 4.2.11 on 2026-04-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_add_status_priority_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='context',
            field=models.JSONField(blank=True, default=dict, verbose_name='Контекст'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='page_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='page_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL страницы'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='Браузер'),
        ),
    ]
