# Generated by Django 4.2.11 on 2026-03-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_427e4b_idx',
            old_name='notif_user_read_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assigned', 'Назначено на вас'), ('deadline_soon', 'Дедлайн завтра'), ('overdue', 'Просрочено'), ('returned', 'Возвращено на доработку'), ('approval_needed', 'Требует согласования'), ('stage_completed', 'Этап завершён'), ('stagnant', 'Без движения')], db_index=True, max_length=30, verbose_name='Тип'),
        ),
    ]
